title: Website
owner: Bhuvan S V
email: bhuvansv44@gmail.com
description: A collection of up-to-date log of my thoughts, timeline and my projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bhuvansv.github.io" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username: absurd_marxist
github_username: bhuvansv
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
